### ISSUE TITLE
Chainlit mounting mechanism fails when FastAPI has root_path. 

### ISSUE THREAD

**Issue by duarteocarmo** [Chainlit/chainlit#1440]
**Describe the bug**
When I use the `root_path` option on my FastAPI application, the chainlit app stops working (it's fetching static assets from the wrong path) 

**To Reproduce**

```python
# chat.py
import chainlit as cl

@cl.on_message
async def main(message: cl.Message):
    # Your custom logic goes here...

    # Send a response back to the user
    await cl.Message(
        content=f"Received: {message.content}",
    ).send()
```

```python
from fastapi import FastAPI
from chainlit.utils import mount_chainlit

app = FastAPI(
    root_path="/api",
)

@app.get("/app")
def read_main():
    return {"message": "Hello World from main app"}


mount_chainlit(app=app, target="chat.py", path="/chainlit")
```

run: `uvicorn app:app --reload`

Go to `http://127.0.0.1:8000/chainlit/` and notice a white screen. 

**Expected behavior**
There's something funky with asset fetching. I tried debugging - but I am not sure what's happening. I do know it's related to assets and staticfiles. 

**Screenshots**
![image](https://github.com/user-attachments/assets/16beca1d-9e65-4e8a-ade1-4344f5dc1bc2)
![image](https://github.com/user-attachments/assets/b3e02d8e-8a20-4ec4-a3d4-1c199c98bd9c)

**Desktop (please complete the following information):**

```
ProductName:            macOS
ProductVersion:         14.6.1
BuildVersion:           23G93
```

**Additional context**
```
➤ pip freeze | grep 'chainlit'
chainlit==1.2.0
```

**Comment by duarteocarmo** [comment]
Could be related to https://github.com/Chainlit/chainlit/issues/1397 (but not sure)

**Comment by duarteocarmo** [comment]
I tested `export CHAINLIT_ROOT_PATH=/api` before running `uvicorn app:app --reload` but same issue persists.

**Comment by alexagr** [comment]
@duarteocarmo you just need to hack `mount_chainlit()` (or create your own version of it) and add FastAPI's root path to CHAINLIT_ROOT_PATH environment variable, e.g.:
```
os.environ["CHAINLIT_ROOT_PATH"] = "/my-root" + path
```

**Comment by willydouhard** [comment]
I think this is fixed with the latest release

**Comment by s-quinn** [comment]
Hello! This still appears to be happening when root_path is set in the FastApi app. 

I am using the following 

python=3.11.3 
chainlit==2.2.1
fastapi=0.115.11

The example provided above results in the issue of the screen being blank when navigating to 
`http://localhost:8000/chainlit/` 

It fails to find any of the assets it needs to render the page 

<img width="1211" alt="Image" src="https://github.com/user-attachments/assets/985306a3-3354-4fe3-8e79-9ca24098b8f2" />


@dokterbob @willydouhard Could we reopen this issue?

**Comment by edify42** [comment]
I'm super happy about this - we have an nginx container in front of our apps and split by path prefix (`/chat/`) and previously we had to setup a dedicated subdomain for chainlit but now this works as intended 👍
