### ISSUE TITLE
Why does the window that pops up locally after I specify the ip and port not display any content？

### ISSUE THREAD

**Issue by lunlu** [Chainlit/chainlit#38]
instruction: chainlit run visualization.py --host xxx.xxx.xx.xx --port 8765 -w

Why does the window that pops up locally after I specify the ip and port not display any content？

**Comment by willydouhard** [comment]
Hello, I would need more info:

- What OS are you running on?
- Are you using a custom host locally?
- Is there any error message in the terminal or in the browser console?

**Comment by kun432** [comment]
this happens in my end. In my case, Try `chainlit hello`, blank page shows in my brower.

- Run Chainlit in a local server and access from my local mac.
  1. Chainlit's default port is already used by another app, so I used `CHAINLIT_PORT=8999 chainlit hello`
  2. Even I stop another app which uses port 8000 and run `chainlit hello`, results are same.
  3. Reloading does not solve. Test with Chrome, Safari, and Edge, results are all same.
- Run Chainlit in VSCode devcontainer + Docker with my local mac, `chainlit hello` works.

My local server: Ubuntu 22.04. Python-3.10.11 with pyenv-virtualenv.

**Comment by lunlu** [comment]
OS:  macOS

I use custom host locally

There is no error message in the terminal and the page.

when I adjust the parameter 'async_mode' :
'''
socketio = SocketIO(
    app,
    cors_allowed_origins="*",
    async_mode="threading",#here, default = "gevent",
    max_http_buffer_size=1000000 * 100,
)
'''
show as below:
<img width="377" alt="image" src="https://github.com/Chainlit/chainlit/assets/30255877/a727a68d-dbb0-48de-8844-4431811deb01">

**Comment by willydouhard** [comment]
> OS: macOS
> 
> I use custom host locally
> 
> There is no error message in the terminal and the page.
> 
> when I adjust the parameter 'async_mode' : ''' socketio = SocketIO( app, cors_allowed_origins="*", async_mode="threading",#here, default = "gevent", max_http_buffer_size=1000000 * 100, ) ''' show as below: <img alt="image" width="377" src="https://user-images.githubusercontent.com/30255877/243674697-a727a68d-dbb0-48de-8844-4431811deb01.png">

So changing the async mode fixes it? That's weird. Also what happens if you try with the default host (not passing --host)? Can you ping on me on discord? It will be easier to go through the problem if that works for you!

**Comment by sebderhy** [comment]
Having the same issue here. Running on a linux server, no error message, just a blank page. Specifying the host and port did not help in any way.

**Comment by SurachaiJaisan** [comment]
Sorachai Jaisan

**Comment by willydouhard** [comment]
> > ระบบปฏิบัติการ: macOS
> > ฉันใช้โฮสต์ที่กำหนดเองในเครื่อง
> > ไม่มีข้อความแสดงข้อผิดพลาดในเทอร์มินัลและเพจ
> > เมื่อฉันปรับพารามิเตอร์ 'async_mode' : ''' socketio = SocketIO( app, cors_allowed_origins="*", async_mode="threading",#here, default = "gevent", max_http_buffer_size=1000000 * 100, ) ''' แสดง ดังต่อไปนี้: <img alt="ภาพ" width="377" src="https://user-images.githubusercontent.com/30255877/243674697-a727a68d-dbb0-48de-8844-4431811deb01.png">

please use english

**Comment by willydouhard** [comment]
Could you try to:

1. install chainlit from the wheel provided in this PR https://github.com/Chainlit/chainlit/pull/40
2. run `chainlit hello`

I would like to see if the rework fix those issues. Note that this version is not merged yet. The infos to install are at the end of the PR's description.

**Comment by marcoszh** [comment]
Same issue here as well.
Runs fine on my macbook, but once deployed on remote server (Ubuntu 20.04), nothing loads.

**Comment by sebderhy** [comment]
@willydouhard I tried and still thave the same issue. 

Is there any workaround to deploy an app with Chainlit today? I really liked Chainlit, but if we can't deploy apps, then that's definitely less useful :( ...

**Comment by willydouhard** [comment]
Should be fixed in the latest version `0.3.0`. Please note that it contains breaking changes. We prepared a [migration guide](https://docs.chainlit.io/migration/0.3.0) to make it easy for everyone.

**Comment by sebderhy** [comment]
I installed it, and `chainlit hello` is still not working...

**Comment by willydouhard** [comment]
Okay, can you DM me on discord so we can debug this live? Will be much easier

**Comment by willydouhard** [comment]
Thanks @sebderhy to I figured the issue. You cannot serve chainlit from a subpath like `https://MY_DOMAIN.com/SUB_PATH`. For now you have to serve it from the root of your domain or subdomain.

**Comment by ruidongtd** [comment]
Running on a linux server, no error message, just a blank page. Specifying the host and port did not help in any way. 
beacause auth0-spa-js must run on a secure origin. See https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin for more information.

**Comment by willydouhard** [comment]
This should be fixed with the latest version of package (0.3.0). Run `pip uninstall chainlit` and then `pip install chainlit` to make sure you have the latest version installed.

**Comment by duyongan** [comment]
I  still have the same issue. 0.5.0

**Comment by willydouhard** [comment]
If you open the console in your blank browser page, does it have any error?

**Comment by srihari0606** [comment]
Hello @willydouhard,

Thank you so much for your research in this space. This is so useful.

However we're facing this issue in the latest version as well. 

We're using <domain>/<subpath> to access the chainlit app that is hosted on EKS. We're getting the blank page when we open the application url and dynamic index.html is looking for the assets at the root level. Screenshot is attached below.

![image](https://github.com/Chainlit/chainlit/assets/84121579/34838da1-be6f-4730-87da-5f1d59e75f74)

**Comment by willydouhard** [comment]
I think this is another issue (we can open a fresh one). At the moment, Chainlit has to be served at the root level (as described [here](https://docs.chainlit.io/cloud/deploy). 

Until it gets fixed, one workaround is to serve it from a subdomain. For instance if you original url is https://mydomain.com/chainlit/app you could created a subdomain https://chainlit.mydomain.com that points to the original url.

**Comment by c3-guillaume-hubert** [comment]
> I think this is another issue (we can open a fresh one). At the moment, Chainlit has to be served at the root level (as described [here](https://docs.chainlit.io/cloud/deploy).
> 
> Until it gets fixed, one workaround is to serve it from a subdomain. For instance if you original url is https://mydomain.com/chainlit/app you could created a subdomain https://chainlit.mydomain.com that points to the original url.

Is this still an issue ? It looks like the problem is still on going on my end
