### ISSUE TITLE
Switching between profiles causes the screen to freeze

### ISSUE THREAD

**Issue by Yahya222** [Chainlit/chainlit#997]
I am using the exact same code with version 1.0.5 and the latest version with the revamped ui.
Using the new version causes the screen to freeze and I cant write messages anymore. To fix it I have to switch to another profile.
It hangs specifically when switching the second profile.
Using the old version with the same code eliminates the bug

**Comment by willydouhard** [comment]
This is fixed in the pre release

**Comment by mentoc3000** [comment]
I'm still seeing this behavior in 1.1.300rc5.

**Comment by mentoc3000** [comment]
Actually, I'm not 100% that it's still happening. For me the behavior was always spurious. I haven't seen it this afternoon, though it was cropping up this morning.
